version: '3'
services:
  web:
    container_name: "api"
    build: 
      context: .
      dockerfile: Dockerfile  
    environment: 
      NODE_ENV: production
      PORT: 80
    ports:
      - 80:80
    links:
      - db
      - redis

  db:
    image: postgres
    container_name: "postgres"
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: movie_rental_prod
 
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
